### ISSUE TITLE
`ArrayIndexOutOfBoundsException` when editing XSD file

### ISSUE THREAD

**Issue by datho7561** [eclipse-lemminx/lemminx#1340]
While editing an XSD file, the following Exception was logged to the output. I was using the binary build on Linux. I wasn't able to figure out how to reproduce it.

```
Message: Unexpected XMLValidator error
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$ElementStack.popElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source)
	at org.apache.xerces.impl.xs.opti.SchemaParsingConfig.parse(Unknown Source)
	at org.apache.xerces.impl.xs.opti.SchemaDOMParser.parse(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.getSchemaDocument(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.eclipse.lemminx.extensions.relaxng.xml.validator.ExternalRelaxNGValidator.startElement(ExternalRelaxNGValidator.java:141)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.eclipse.lemminx.extensions.xerces.ExternalXMLDTDValidator.startElement(ExternalXMLDTDValidator.java:80)
	at org.eclipse.lemminx.extensions.xerces.xmlmodel.XMLModelHandler.startElement(XMLModelHandler.java:227)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.parseXML(XMLValidator.java:318)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:132)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:58)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:67)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:49)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:173)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:187)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:662)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$29(XMLTextDocumentService.java:598)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$30(XMLTextDocumentService.java:596)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

**Comment by datho7561** [comment]
It seems related to the RelaxNG support, but I wasn't editing a RelaxNG document. Here was the document I had:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="childA" minOccurs="1" maxOccurs="1"></xs:element>
        <xs:element ref="childB" minOccurs="0" maxOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="childA">
    <xs:complexType>
      <xs:attribute name="asdf" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="en">
              <xs:annotation>
                <xs:documentation>asdf</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="de">
              <xs:annotation>
                <xs:documentation>asdf but in german</xs:documentation>
              </xs:annotation>
            </xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="hjkl"></xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="childB">
    <xs:complexType>
      <xs:attribute name="asdf" use="required"></xs:attribute>
      <xs:attribute name="hjkl"></xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

**Comment by angelozerr** [comment]
@datho7561 I cannot reproduce it -(

Why are you saying it is because of RelaxNG? if you say that because in the trace you see:

`at org.eclipse.lemminx.extensions.relaxng.xml.validator.ExternalRelaxNGValidator.startElement`

it is normal it is just validator pipeline which delegate the startElement to another pipeline.

**Comment by datho7561** [comment]
> if you say that because in the trace you see:

Yes, that's the only reason I had. maybe it is something else, then.

**Comment by angelozerr** [comment]
I spend my time to try to reproduce but without success -( Could you reproduce it?

**Comment by datho7561** [comment]
No, I couldn't reproduce it easily. I'll try to reproduce it for a while today.
