### ISSUE TITLE
schemaLocation with trailing `\` causes telemetry to error

### ISSUE THREAD

**Issue by datho7561** [eclipse-lemminx/lemminx#1358]
Given:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans
  xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:util="http://www.springframework.org/schema/util"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
                      http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd\">


</beans>
```

(note the trailing `\` in the file location for the second schema referenced)

The following Exception gets logged:

```
Message: Error while processing didOpen for the participant 'org.eclipse.lemminx.extensions.contentmodel.participants.DocumentTelemetryParticipant'.
org.eclipse.lemminx.uriresolver.InvalidURIException: The 'http://www.springframework.org/schema/util/spring-util.xsd\' URI cannot be parsed: Illegal character in path at index 58: http://www.springframework.org/schema/util/spring-util.xsd\
	at org.eclipse.lemminx.uriresolver.CacheResourcesManager.getResourceCachePath(CacheResourcesManager.java:306)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.fillReferencedGrammarInfo(ContentModelManager.java:268)
	at org.eclipse.lemminx.extensions.contentmodel.model.ContentModelManager.getReferencedGrammarInfos(ContentModelManager.java:233)
	at org.eclipse.lemminx.telemetry.DocumentTelemetryInfo.collectDocumentTelemetryInfo(DocumentTelemetryInfo.java:42)
	at org.eclipse.lemminx.telemetry.TelemetryManager.onDidOpen(TelemetryManager.java:65)
	at org.eclipse.lemminx.extensions.contentmodel.participants.DocumentTelemetryParticipant.didOpen(DocumentTelemetryParticipant.java:32)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$validate$31(XMLTextDocumentService.java:640)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$validate$32(XMLTextDocumentService.java:638)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by zafar-hussain** [comment]
hi @datho7561,

there are 17 places where this schema file location with a forward slash is used in the test XSIFormatterExperimentalTest.java,

should all these 17 forward slashes be removed?

cheers

**Comment by haseeb-xd** [comment]
I wanna work on this, all I gotta do is to remove the trailing `\` right?

**Comment by datho7561** [comment]
Thanks @haseeb-xd! I'll try to give a better description of the error.

The main idea is that somewhere (I'll update this message with the exact spot in the code base using the stack trace) we try to convert every second entry of the `xsi:schemaLocation` attribute to a URL. However, if the entry is not a proper URL, an Exception will be thrown.

We should prevent this exception from being logged by catching the Exception. It shouldn't be logged, because it's not abnormal for an XML document to have syntax errors in it while it's being edited.

**Comment by datho7561** [comment]
@haseeb-xd okay, I added more details. Feel free to ask any questions you have!

**Comment by Satyamkumarnavneet** [comment]
Hello @datho7561, I would like to work on this issue

**Comment by datho7561** [comment]
Thanks! Feel free to ask any questions you have, and to ping me on the PR for review once it's ready.

**Comment by Satyamkumarnavneet** [comment]
Hii @datho7561 Can you please tell me how to install this project locally I was using IntelliJ IDEA and I got many errors while building the project. And how to test that I have made the right changes in the code.

**Comment by datho7561** [comment]
@Satyamkumarnavneet Take a look at https://github.com/eclipse/lemminx/blob/main/CONTRIBUTING.md if you haven't yet.

The main idea is that this repository is a Maven project. I haven't used Intellij much, but you should be able to import the root folder as a Maven project. If you give me more information on what errors you are seeing, I might be able to help a bit more.

Also, make sure that you can build the project on command line with `./mvnw clean verify` (Linux/macOS) or `mvnw.cmd clean verify` (Windows). This will compile the project into a `.jar`, and it will run the tests.

The way that I test the changes is by using lemminx in VS Code through the vscode-xml project. [Here](https://github.com/redhat-developer/vscode-xml/blob/main/CONTRIBUTING.md#how-to-contribute) is more information on how to set up vscode-xml and test lemminx using it. You can also test it through other LSP-enabled editors like neovim or emacs, but the process is best documented for VS Code.

I will follow up with some steps for adding unit tests for the change...

**Comment by Satyamkumarnavneet** [comment]
![Screenshot (441)](https://user-images.githubusercontent.com/76639713/216027718-600c2796-3c76-4f39-8b6c-fabc80ba9e2a.png)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project org.eclipse.lemminx: Compilation failure: Compilation failure:
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/GenerateDocTypeCodeActionResolver.java:[36,56] cannot find symbol
[ERROR]   symbol: class AbstractGenerateGrammarAndAssociationResolveCodeActionParticipant
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[67,51] cannot find symbol
[ERROR]   symbol:   variable GenerateXSINoNamespaceSchemaCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[68,37] cannot find symbol
[ERROR]   symbol:   class GenerateXSINoNamespaceSchemaCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[69,51] cannot find symbol
[ERROR]   symbol:   variable GenerateXMLModelWithXSDCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[70,37] cannot find symbol
[ERROR]   symbol:   class GenerateXMLModelWithXSDCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[72,33] incompatible types: org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.GenerateDocTypeCodeActionResolver cannot be converted to org.eclipse.lemminx.services.extensions.codeaction.ICodeActionResolvesParticipant
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[73,51] cannot find symbol
[ERROR]   symbol:   variable GenerateXMLModelWithDTDCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[74,37] cannot find symbol
[ERROR]   symbol:   class GenerateXMLModelWithDTDCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[75,51] cannot find symbol
[ERROR]   symbol:   variable GenerateRelaxNGSchemaCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[76,37] cannot find symbol
[ERROR]   symbol:   class GenerateRelaxNGSchemaCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[108,41] cannot find symbol
[ERROR]   symbol:   variable GenerateXMLModelWithXSDCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[129,41] cannot find symbol
[ERROR]   symbol:   variable GenerateXMLModelWithDTDCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[177,41] cannot find symbol
[ERROR]   symbol:   variable GenerateXSINoNamespaceSchemaCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/NoGrammarConstraintsCodeAction.java:[222,41] cannot find symbol
[ERROR]   symbol:   variable GenerateRelaxNGSchemaCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.nogrammarconstraints.NoGrammarConstraintsCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/GenerateDocTypeCodeActionResolver.java:[40,9] method does not override or implement a method from a supertype
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/nogrammarconstraints/GenerateDocTypeCodeActionResolver.java:[46,9] method does not override or implement a method from a supertype
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/missingelement/required_elements_missing_expectedCodeAction.java:[66,51] cannot find symbol
[ERROR]   symbol:   variable required_elements_missing_expectedCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.missingelement.required_elements_missing_expectedCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/missingelement/required_elements_missing_expectedCodeAction.java:[67,37] cannot find symbol
[ERROR]   symbol:   class required_elements_missing_expectedCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.missingelement.required_elements_missing_expectedCodeAction
[ERROR] /C:/Users/satyam kumar navneet/Documents/Satyam document/GSOC/The-Eclipse-Foundation/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/missingelement/required_elements_missing_expectedCodeAction.java:[119,41] cannot find symbol
[ERROR]   symbol:   variable required_elements_missing_expectedCodeActionResolver
[ERROR]   location: class org.eclipse.lemminx.extensions.contentmodel.participants.codeactions.missingelement.required_elements_missing_expectedCodeAction
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.eclipse.lemminx



Now I am getting this error, please have a look

**Comment by Satyamkumarnavneet** [comment]
In `missingelement` there are only four java files:  
```
1. MissingElementDataConstants 
2. required_element_missingCodeAction 
3. required_element_missingCodeActionResolver
4. required_elements_missing_expectedCodeAction
```

**Comment by fbricon** [comment]
You have one file missing from https://github.com/eclipse/lemminx/tree/main/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/participants/codeactions/missingelement. 

Try `git reset --hard origin main`

**Comment by Satyamkumarnavneet** [comment]
Yes, that file is missing when I used `git status` it shows lots of files are deleted...

![Screenshot (442)](https://user-images.githubusercontent.com/76639713/216080895-b05e52ff-92ca-47a7-95b7-5d95bdc0f0d3.png)
