### ISSUE TITLE
NPE with XSDValidator

### ISSUE THREAD

**Issue by angelozerr** [eclipse-lemminx/lemminx#437]
It seems that there is a NPE with this XSD file (xs:element name attribute value is empty) when XSDValidator is executed:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="testType">     
		<xs:all>
			<xs:element name="" minOccurs="1" maxOccurs="2" type="xs:string"/>
		</xs:all>
	</xs:complexType>
</xs:schema>
```

**Comment by fbricon** [comment]
```
[Error - 9:22:29 AM] Jun 13, 2019 09:22:29 org.eclipse.lsp4xml.extensions.xsd.participants.diagnostics.XSDValidator doDiagnostics()
Message: Unexpected XSDValidator error
java.lang.NullPointerException
	at org.apache.xerces.impl.xs.traversers.XSDAbstractTraverser.checkOccurrences(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDElementTraverser.traverseLocal(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.traverseLocalElements(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadGrammar(Unknown Source)
	at org.eclipse.lsp4xml.extensions.xsd.participants.diagnostics.LSPXMLGrammarPreparser.preparseGrammar(LSPXMLGrammarPreparser.java:53)
	at org.eclipse.lsp4xml.extensions.xsd.participants.diagnostics.XSDValidator.doDiagnostics(XSDValidator.java:90)
	at org.eclipse.lsp4xml.extensions.xsd.participants.diagnostics.XSDDiagnosticsParticipant.doDiagnostics(XSDDiagnosticsParticipant.java:38)
	at org.eclipse.lsp4xml.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:83)
	at org.eclipse.lsp4xml.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:51)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:142)
	at org.eclipse.lsp4xml.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:151)
	at org.eclipse.lsp4xml.XMLTextDocumentService.validate(XMLTextDocumentService.java:401)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$triggerValidationFor$19(XMLTextDocumentService.java:394)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The NPE is in the Xerces layer, nothing we can do about it

**Comment by angelozerr** [comment]
> The NPE is in the Xerces layer, nothing we can do about it

perhaps which should skip log of NPE?
